
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 9;
  public static final int FUNCTION = 42;
  public static final int LKEY = 21;
  public static final int LBRA = 19;
  public static final int COMMENT = 45;
  public static final int SMALLER = 12;
  public static final int SEMI = 3;
  public static final int FOR = 33;
  public static final int MINUS = 6;
  public static final int AND = 17;
  public static final int RPAR = 5;
  public static final int TYPE = 39;
  public static final int VIRG = 24;
  public static final int NIL = 26;
  public static final int IN = 37;
  public static final int OR = 18;
  public static final int SMALLER_EQUAL = 15;
  public static final int NUM = 2;
  public static final int PLUS = 7;
  public static final int ASSIGN = 10;
  public static final int IF = 28;
  public static final int ID = 43;
  public static final int DOT = 25;
  public static final int OF = 27;
  public static final int EOF = 0;
  public static final int EQUAL = 13;
  public static final int RKEY = 22;
  public static final int error = 1;
  public static final int BIGGER_EQUAL = 14;
  public static final int RBRA = 20;
  public static final int BREAK = 35;
  public static final int BIGGER = 11;
  public static final int TIMES = 8;
  public static final int COLON = 23;
  public static final int ELSE = 30;
  public static final int TO = 34;
  public static final int WHILE = 31;
  public static final int LET = 36;
  public static final int THEN = 29;
  public static final int ARRAY_OF = 40;
  public static final int END = 38;
  public static final int STRING = 44;
  public static final int LPAR = 4;
  public static final int DIFF = 16;
  public static final int VAR = 41;
  public static final int DO = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUM",
  "SEMI",
  "LPAR",
  "RPAR",
  "MINUS",
  "PLUS",
  "TIMES",
  "DIVIDE",
  "ASSIGN",
  "BIGGER",
  "SMALLER",
  "EQUAL",
  "BIGGER_EQUAL",
  "SMALLER_EQUAL",
  "DIFF",
  "AND",
  "OR",
  "LBRA",
  "RBRA",
  "LKEY",
  "RKEY",
  "COLON",
  "VIRG",
  "DOT",
  "NIL",
  "OF",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "TO",
  "BREAK",
  "LET",
  "IN",
  "END",
  "TYPE",
  "ARRAY_OF",
  "VAR",
  "FUNCTION",
  "ID",
  "STRING",
  "COMMENT"
  };
}

